// ============================================================================
//  harness/main_sim.cpp  --  the laptop-side entry point
// ----------------------------------------------------------------------------
//  Replaces main.cpp. The real one is full of competition callbacks, a screen
//  selector loop and a driver-control loop, none of which we want. This one
//  does three things: build the chassis, run one routine, write the log.
//
//  Usage:  vexsim.exe <routine> [output.json]
// ============================================================================
#include "vex.h"
#include "recorder.h"
#include <cstring>
#include <cstdio>
#include <string>
#include <fstream>

// --- COPIED VERBATIM FROM src/main.cpp ---------------------------------------
// Not retyped. The wheel diameter, gear ratio and gyro scale below are the
// robot's real calibration constants, and this is the only place they appear
// in the simulator. If the robot's configuration changes, this block is
// re-copied and everything downstream follows.
Drive chassis(

ZERO_TRACKER_ODOM,

motor_group(leftA, leftB, leftC),

motor_group(rightA, rightB, rightC),

PORT11,      // 惯性传感器端口

3.25,        // 输入轮子的直径

0.75,        // 输入齿轮/输出齿轮算出齿轮比

360,         // 陀螺仪比例
//左轮前后端口     右轮前后端口
PORT1,     -PORT3,

PORT10,     -PORT2,
//下面默认就可以了
3,

2.75,

-2,

1,

-2.75,

5.5

);
// --- END COPIED BLOCK --------------------------------------------------------

struct Routine { const char* name; void (*fn)(); };

// The same five routines main.cpp's selector switch can reach, plus `test`.
static const Routine ROUTINES[] = {
  {"zuo",       zuo},
  {"superzuo",  superzuo},
  {"lanyou",    lanyou},
  {"superyou",  superyou},
  {"skillszuo", skillszuo},
  {"test",      test},
};
static const int N_ROUTINES = sizeof(ROUTINES) / sizeof(ROUTINES[0]);

// Runs every routine and writes out/logs.js -- one JavaScript file assigning a
// global object.
//
// Why a .js file and not the .json: a page opened with file:// is forbidden by
// the browser's same-origin policy from fetch()ing a local file, but it is
// allowed to load a <script>. Emitting the same data as an assignment means
// the viewer works by double-clicking index.html, with no local web server.
// The .json files are still written, for git and for any other consumer.
static void build_all() {
  std::ofstream js("out/logs.js");
  if (!js) { std::printf("ERROR: cannot write out/logs.js\n"); return; }

  js << "// Generated by vexsim.exe -- do not edit by hand.\n";
  js << "window.VEXSIM_LOGS = {\n";

  for (int i = 0; i < N_ROUTINES; ++i) {
    // `chassis` is a global, so its gains and timeouts survive from one
    // routine to the next. The real robot avoids this because pre_auton()
    // calls default_constants() before any auton runs (main.cpp:88). Doing the
    // same here stops routine N inheriting routine N-1's leftover timeouts --
    // which matters for test(), the one routine that does not set its own.
    default_constants();
    sim::reset();                       // wipe log + clock AFTER that setup,
                                        // so the log starts at the routine
    ROUTINES[i].fn();                   // runs the unmodified autons.cpp

    std::string json = sim::build_json(ROUTINES[i].name);
    js << "  \"" << ROUTINES[i].name << "\": " << json
       << (i + 1 < N_ROUTINES ? "," : "") << "\n";

    std::string path = std::string("out/") + ROUTINES[i].name + ".json";
    sim::write_log(path, ROUTINES[i].name);
    std::printf("  %-22s %3zu actions  %7.0f ms\n",
                ROUTINES[i].name, sim::action_count(), vex::sim_now_ms());
  }

  js << "};\n";
  std::printf("wrote out/logs.js  (%d routines)\n", N_ROUTINES);
}

int main(int argc, char** argv) {
  // No argument, or --all: build everything the viewer needs.
  if (argc < 2 || std::strcmp(argv[1], "--all") == 0) {
    build_all();
    return 0;
  }

  const char* want = argv[1];
  std::string out  = (argc >= 3) ? argv[2] : (std::string("out/") + want + ".json");

  for (int i = 0; i < N_ROUTINES; ++i) {
    if (std::strcmp(ROUTINES[i].name, want) == 0) {
      // This call runs the UNMODIFIED autons.cpp. Everything it touches
      // resolves to the mock, so nothing moves and everything is recorded.
      ROUTINES[i].fn();
      sim::write_log(out, want);
      std::printf("wrote %s  (%zu actions, %.0f ms simulated)\n",
                  out.c_str(), sim::action_count(), vex::sim_now_ms());
      return 0;
    }
  }

  std::printf("unknown routine '%s'\navailable:\n", want);
  for (int i = 0; i < N_ROUTINES; ++i) std::printf("  %s\n", ROUTINES[i].name);
  return 1;
}
